on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: 3.13
        cache: 'pip'
      
    - name: Install dependencies
      run: |
        df -h
        python -m pip install --upgrade pip setuptools
        python -m pip install pyinstaller
        python -m pip install -e .
        df -h
    
    - name: Clean up and remove nvidia
      # PyInstaller tries to include the CUDA/Nvidia modules if they exist, but we don't want that
      # because it's way too big.
      if: runner.os == 'Linux'
      run: |
        python -m pip uninstall --yes nvidia-cusparselt-cu12 nvidia-nvtx-cu12 nvidia-nvshmem-cu12 nvidia-nvjitlink-cu12 nvidia-nccl-cu12 nvidia-curand-cu12 nvidia-cufile-cu12 nvidia-cuda-runtime-cu12 nvidia-cuda-nvrtc-cu12 nvidia-cuda-cupti-cu12 nvidia-cublas-cu12 nvidia-cusparse-cu12 nvidia-cufft-cu12 nvidia-cudnn-cu12 nvidia-cusolver-cu12
        df -h
        
    - name: Compile executable
      run: |
        pyinstaller MDToy.spec
        df -h

    - name: Create tarballs (macOS only)
      if: runner.os == 'macOS'
      run: |
        tar -czf MDToy-macos-dir.tar.gz -C dist MDToy
        tar -czf MDToy-macos-app.tar.gz -C dist MDToy.app
    
    - name: Create tarball (Ubuntu only)
      if: runner.os == 'Linux'
      run: tar -czf MDToy-ubuntu.tar.gz -C dist MDToy

    - uses: actions/upload-artifact@v5
      if: runner.os == 'macOS'
      with:
        name: MDToy-${{ matrix.os }}-dir
        path: MDToy-macos-dir.tar.gz
        compression-level: 0

    - uses: actions/upload-artifact@v5
      if: runner.os == 'macOS'
      with:
        name: MDToy-${{ matrix.os }}-app
        path: MDToy-macos-app.tar.gz
        compression-level: 0
    
    - uses: actions/upload-artifact@v5
      if: runner.os == 'Windows'
      with:
        name: MDToy-${{ matrix.os }}
        path: dist/*
    
    - uses: actions/upload-artifact@v5
      if: runner.os == 'Linux'
      with:
        name: MDToy-${{ matrix.os }}
        path: MDToy-ubuntu.tar.gz
        compression-level: 0
